const SUPABASE_URL="https://efpfhpwxmzpmmynczbce.supabase.co";
const SUPABASE_ANON_KEY="sb_publishable_7pNQIr21sL3EUy0WSqXKwQ_N6_oDWhJ";
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function toast(msg){const el=$("toast");el.textContent=msg;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function setStatus(text,ok=true){$("connectionStatus").textContent=text;$("statusDot").className="status-dot "+(ok?"ok":"bad")}
function switchTab(type){const login=type==="login";$("loginForm").classList.toggle("hidden",!login);$("signupForm").classList.toggle("hidden",login);$("loginTab").classList.toggle("active",login);$("signupTab").classList.toggle("active",!login)}
$("loginTab").onclick=()=>switchTab("login");$("signupTab").onclick=()=>switchTab("signup");
function showLoggedOut(){$("authArea").classList.remove("hidden");$("appArea").classList.add("hidden");$("bottomNav").classList.add("hidden");$("walletChip").classList.add("hidden");$("logoutBtn").classList.add("hidden");$("sessionBadge").textContent="Khách"}
function showLoggedIn(user,p){$("authArea").classList.add("hidden");$("appArea").classList.remove("hidden");$("bottomNav").classList.remove("hidden");$("walletChip").classList.remove("hidden");$("logoutBtn").classList.remove("hidden");const bal=Number(p.balance||0).toLocaleString("vi-VN");$("sessionBadge").textContent=p.username||"Player";$("headerBalance").textContent=bal;$("heroBalance").textContent=bal+" NXC";$("heroRole").textContent=String(p.role||"player").toUpperCase();$("profileUsername").textContent=p.username||"Player";$("profileEmail").textContent=user.email||"";$("profileBalance").textContent=bal+" NXC";$("profileRole").textContent=String(p.role||"player").toUpperCase();$("profileAvatar").textContent=(p.username||"N").slice(0,1).toUpperCase();$("adminArea").classList.toggle("hidden",p.role!=="admin")}
async function getProfile(id){const {data,error}=await sb.from("profiles").select("*").eq("id",id).single();if(error)throw error;return data}
async function refresh(){try{const {data:{session},error}=await sb.auth.getSession();if(error)throw error;setStatus("Đã kết nối Supabase ✓",true);if(!session){showLoggedOut();return}const p=await getProfile(session.user.id);if(p.is_suspended){await sb.auth.signOut();alert("Tài khoản đang bị khóa.");showLoggedOut();return}showLoggedIn(session.user,p);await loadTransactions(session.user.id);await loadLeaderboard();if(p.role==="admin")await loadPlayers()}catch(err){console.error(err);setStatus("Lỗi kết nối: "+err.message,false)}}
$("signupForm").onsubmit=async e=>{e.preventDefault();try{const username=$("signupUsername").value.trim(),email=$("signupEmail").value.trim(),password=$("signupPassword").value;const {data,error}=await sb.auth.signUp({email,password,options:{data:{username}}});if(error)throw error;if(data.session){toast("Tạo tài khoản thành công");await refresh()}else alert("Đã tạo tài khoản. Hãy kiểm tra email để xác nhận.")}catch(err){alert(err.message)}};
$("loginForm").onsubmit=async e=>{e.preventDefault();try{const {error}=await sb.auth.signInWithPassword({email:$("loginEmail").value.trim(),password:$("loginPassword").value});if(error)throw error;await refresh()}catch(err){alert(err.message)}};
$("logoutBtn").onclick=async()=>{await sb.auth.signOut();showLoggedOut()};
async function loadTransactions(userId){const el=$("transactionList");const {data,error}=await sb.from("coin_transactions").select("*").eq("player_id",userId).order("created_at",{ascending:false}).limit(8);if(error){console.error(error);el.innerHTML='<p class="muted">Chưa tải được lịch sử.</p>';return}el.innerHTML=data?.length?data.map(t=>{const amount=Number(t.amount||0);return `<div class="tx-row"><div><strong>${amount>0?"+":""}${amount.toLocaleString("vi-VN")} NXC</strong><span>${esc(t.reason||t.type||"Giao dịch")}</span></div><span>${new Date(t.created_at).toLocaleDateString("vi-VN")}</span></div>`}).join(""):'<p class="muted">Chưa có giao dịch.</p>'}
async function loadLeaderboard(){const el=$("leaderboardList");let {data,error}=await sb.rpc("admin_list_players",{search_text:null});if(error){const res=await sb.from("profiles").select("username,balance,role").order("balance",{ascending:false}).limit(10);data=res.data;error=res.error}if(error){el.innerHTML='<p class="muted">Chưa tải được bảng xếp hạng.</p>';return}const rows=(data||[]).filter(p=>p.role!=="admin").sort((a,b)=>Number(b.balance||0)-Number(a.balance||0)).slice(0,10);el.innerHTML=rows.length?rows.map((p,i)=>`<div class="rank-row"><div class="rank-left"><div class="rank-num">${i+1}</div><div><strong>${esc(p.username||"Player")}</strong><span>PLAYER</span></div></div><strong>${Number(p.balance||0).toLocaleString("vi-VN")} NXC</strong></div>`).join(""):'<p class="muted">Chưa có người chơi để xếp hạng.</p>'}
$("refreshLeaderboard").onclick=loadLeaderboard;
async function loadPlayers(search=""){const el=$("playerList");const {data,error}=await sb.rpc("admin_list_players",{search_text:search||null});if(error){el.innerHTML='<p class="muted">'+esc(error.message)+'</p>';return}el.innerHTML=data?.length?data.map(p=>`<div class="player-row"><div><strong>${esc(p.username||"Player")}</strong><span>${Number(p.balance||0).toLocaleString("vi-VN")} NXC · ${p.is_suspended?"Đã khóa":p.role}</span></div>${p.role==="admin"?'<span class="admin-pill">ADMIN</span>':`<div class="player-actions"><button class="add" onclick="adjustNxc('${p.id}',1000)">+1K</button><button class="sub" onclick="adjustNxc('${p.id}',-1000)">-1K</button><button class="lock" onclick="setSuspended('${p.id}',${!p.is_suspended})">${p.is_suspended?"Mở khóa":"Khóa"}</button></div>`}</div>`).join(""):'<p class="muted">Chưa có tài khoản.</p>'}
window.adjustNxc=async(id,amount)=>{const reason=prompt("Lý do điều chỉnh NXC:","Admin adjustment");if(reason===null)return;const {error}=await sb.rpc("admin_adjust_balance",{target_player_id:id,delta_amount:amount,adjustment_reason:reason||"Admin adjustment"});if(error){alert(error.message);return}toast(amount>0?"Đã cộng NXC":"Đã trừ NXC");await loadPlayers($("playerSearch").value);await loadLeaderboard()};
window.setSuspended=async(id,suspended)=>{if(!confirm(suspended?"Khóa tài khoản này?":"Mở khóa tài khoản này?"))return;const {error}=await sb.rpc("admin_set_suspended",{target_player_id:id,suspended});if(error){alert(error.message);return}toast(suspended?"Đã khóa tài khoản":"Đã mở khóa tài khoản");await loadPlayers($("playerSearch").value)};
$("playerSearch").oninput=e=>loadPlayers(e.target.value);
document.querySelectorAll(".category").forEach(btn=>{btn.onclick=()=>{document.querySelectorAll(".category").forEach(b=>b.classList.remove("active"));btn.classList.add("active");const f=btn.dataset.filter;document.querySelectorAll(".game-card").forEach(card=>card.classList.toggle("hidden",f!=="all"&&card.dataset.category!==f))}});
document.querySelectorAll(".play-btn").forEach(btn=>{btn.onclick=()=>toast(btn.dataset.game==="Baccarat"?"Baccarat sẽ là game đầu tiên mình nối tiếp.":btn.dataset.game+" đang được phát triển.")});
document.querySelectorAll(".nav-item").forEach(item=>{item.onclick=()=>{document.querySelectorAll(".nav-item").forEach(n=>n.classList.remove("active"));item.classList.add("active")}});
sb.auth.onAuthStateChange(()=>setTimeout(refresh,0));refresh();
