create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,username text not null unique check(char_length(username) between 3 and 24),role text not null default 'player' check(role in('player','admin')),balance bigint not null default 10000 check(balance>=0),is_suspended boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.coin_transactions(id uuid primary key default gen_random_uuid(),player_id uuid not null references public.profiles(id) on delete cascade,amount bigint not null,type text not null default 'admin_adjustment',reason text not null,created_by uuid references public.profiles(id),created_at timestamptz not null default now());
create index if not exists coin_transactions_player_idx on public.coin_transactions(player_id,created_at desc);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ declare u text; begin u:=nullif(trim(new.raw_user_meta_data->>'username'),''); if u is null then u:='Player_'||substr(new.id::text,1,8); end if; insert into public.profiles(id,username,balance) values(new.id,u,10000); insert into public.coin_transactions(player_id,amount,type,reason,created_by) values(new.id,10000,'welcome_bonus','NXC khởi tạo tài khoản',new.id); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin' and is_suspended=false); $$;
alter table public.profiles enable row level security; alter table public.coin_transactions enable row level security;
drop policy if exists "read own profile" on public.profiles; create policy "read own profile" on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin());
drop policy if exists "read own transactions" on public.coin_transactions; create policy "read own transactions" on public.coin_transactions for select to authenticated using(player_id=auth.uid() or public.is_admin());
create or replace view public.admin_players_view with(security_invoker=true) as select p.id,p.username,u.email,p.role,p.balance,p.is_suspended,p.created_at from public.profiles p left join auth.users u on u.id=p.id; grant select on public.admin_players_view to authenticated;
create or replace function public.admin_adjust_balance(target_player_id uuid,delta_amount bigint,adjustment_reason text) returns bigint language plpgsql security definer set search_path=public as $$ declare new_balance bigint; begin if not public.is_admin() then raise exception 'admin only'; end if; if delta_amount=0 then raise exception 'amount cannot be zero'; end if; update public.profiles set balance=balance+delta_amount where id=target_player_id and balance+delta_amount>=0 returning balance into new_balance; if new_balance is null then raise exception 'player not found or insufficient balance'; end if; insert into public.coin_transactions(player_id,amount,type,reason,created_by) values(target_player_id,delta_amount,'admin_adjustment',trim(adjustment_reason),auth.uid()); return new_balance; end; $$; revoke all on function public.admin_adjust_balance(uuid,bigint,text) from public; grant execute on function public.admin_adjust_balance(uuid,bigint,text) to authenticated;
create or replace function public.admin_set_suspended(target_player_id uuid,suspended boolean) returns void language plpgsql security definer set search_path=public as $$ begin if not public.is_admin() then raise exception 'admin only'; end if; if exists(select 1 from public.profiles where id=target_player_id and role='admin') then raise exception 'cannot suspend admin'; end if; update public.profiles set is_suspended=suspended where id=target_player_id; end; $$; revoke all on function public.admin_set_suspended(uuid,boolean) from public; grant execute on function public.admin_set_suspended(uuid,boolean) to authenticated;
-- Sau khi bạn đăng ký tài khoản của mình, chạy lệnh này và thay email:
-- update public.profiles set role='admin' where id=(select id from auth.users where email='EMAIL_CUA_BAN@example.com');
